### ISSUE TITLE
looking reseller ?

### ISSUE THREAD

**Issue by orangekushqc** [1310s/FortniteRageCheatSource#9]
hello to you I wanted to know if you would like to partner with me? I have no experience in C++, C# but I have my discord server and 126 members, I can do a lot of advertising and a lot of sales! I'm looking for someone with experience in dev because we will need EAC bypass + Hwid Login ect.. if you're interested here is my discord:
FastMatikQc#6560 and my server discord : https://discord.gg/qz3Dzxc6Dc

**Comment by 1310s** [comment]
hello sir, thanks for the offer but im not working on cheats for now.
